### ISSUE TITLE
Run the include-expansion discovery pass in parallel without changing output

### ISSUE THREAD

**Issue by devnullexile** [Last-Humans-Coding-Under-White-Nights/pathologist#88]
## Summary

Indexing runs one phase on a single thread while everything around it is parallel: the pass that discovers which macro-expansion variants each header needs. On the camera corpus it is 1.3s of a 6.1s run at `--jobs 8`; on HDF about 1.0s of 4.0s. As the other phases get faster or more cores are added, this pass becomes the floor.

The eval report names the redesign that would fix it and records that it was not attempted.

## In plain words

Before the tool can read a C/C++ file, it has to run the preprocessor: paste in the headers, apply the `#define`s, pick the `#if` branches. Headers are shared by many files, so the tool caches each header's expanded form and reuses it. But a header can expand differently depending on which file includes it, so a first "discovery" pass walks every file in order and records the variants. That pass writes to the cache while reading it, and running it on several threads at once was tried and produced different results run to run. So it stays single-threaded, and the whole machine waits for it.

## What was measured

From the second performance round (2026-09-11), camera at `--jobs 8`, wall 6.1-6.4s:

| phase | time | parallel? |
|---|---:|---|
| discovery pass | 1.3s | no |
| warm pass | 0.9s | no |
| export | 0.6s | no |
| everything else | ~3.3s | yes |

A previous attempt to run discovery in parallel as-is moved camera across 20,299 / 20,326 / 20,847 direct edges on three runs of one tree, which is why it is serial today.

## Expected behavior

- The discovery pass runs on the worker pool, and a cached expansion depends only on header content, language and the macro fingerprint at the point of inclusion, never on the order in which files happened to be processed.
- Output is bit-identical across three `--jobs 8` runs, one `--jobs 1` run and the current master binary, on all three pinned corpora. This is the whole acceptance bar: a speed-up that changes any edge is a bug.
- Camera wall at `--jobs 8` drops by roughly the pass's current cost; HDF and hiview move in proportion.

## Acceptance

- [ ] Design note in `docs/PREPROCESSOR.md` describing the cache key and why insertion order cannot affect what a translation unit sees.
- [ ] `preprocess-done` timing still reports the pass separately so the gain is attributable.
- [ ] `python3 scripts/eval_check.py` passes 90/90; every exact metric and dispatch-site count unchanged.
- [ ] DB dumps byte-identical across three `--jobs 8` runs, one `--jobs 1` run and the previous binary, on all three corpora.
- [ ] Timing table in `docs/EVAL_REPORT.md` updated in the same sitting as a master measurement on the same machine.

## Where to start

- `crates/trace-parse/src/configured.rs` and `crates/trace-parse/src/index_cache.rs`: the two-pass scheme and the shared expansion cache.
- `crates/trace-preproc`: `MacroFingerprint::signature` and the include-expansion cache key.
- `docs/EVAL_REPORT.md`, the "Regression investigation, 2026-09-10" and "Second performance round, 2026-09-11" blocks, which give the sample profiles and list what is left in the pass (`stat` on first probes, fingerprint hashing, hide-set hashing).
- `docs/PREPROCESSOR.md` for the current cache contract.

Not in scope: the warm pass and export, which are separate serial costs.
